# Generated by Django 4.0.1 on 2022-01-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_reloan', 'You can renew this book loan.'),)},
        ),
    ]
